### PR TITLE
`expound/def` takes error message string or function

### PR DESCRIPTION
**Pull request by bhb**
Fixes https://github.com/bhb/expound/issues/74

### CODE REVIEW

**Comment by bhb** [comment]
@ikitommi Would this work for your purposes? Try this:

`rlwrap clojure -Sdeps "{:deps {metosin/spec-tools {:mvn/version \"0.7.0\"} expound/expound {:git/url \"https://github.com/bhb/expound.git\" :sha \"2a0aa0e96c6b1f202cac3102e1b272d8df8d1996\"}}}"`

```
user=> (require '[clojure.spec.alpha :as s] '[expound.alpha :as expound] '[spec-tools.core :as st])
nil
user=> (set! s/*explain-out* expound/printer)
#object[expound.alpha$printer 0x719843e5 "expound.alpha$printer@719843e5"]
user=> (expound/def ::my-num (st/spec pos-int? {:reason "positive"}) (fn [problem] (str "should be " (:reason problem))))
:user/my-num
user=> (s/explain ::my-num -1)
-- Spec failed --------------------

  -1

should be positive

-- Relevant specs -------

:user/my-num:
  (spec-tools.core/spec
   {:spec clojure.core/pos-int?, :type :long, :reason "positive"})

-------------------------
Detected 1 error
nil
```

Unfortunately, I'm not sure this can be made to work on extra keys in `s/keys` spec, since unless we have access to a different type of spec e.g. a `strict-key`, `explain` will just "success" on extra keys.

**Comment by bhb** [comment]
@ikitommi OK, I've changed this slightly to pass in the old message for preds (not used below, but I've updated the callback):

```
rlwrap clojure -Sdeps "{:deps {metosin/spec-tools {:mvn/version \"0.7.0\"} expound/expound {:git/url \"https://github.com/bhb/expound.git\" :sha \"579d31fd8fb3e83b0e08bbb24e7e61cf90192843\"}}}"
```

```
user=>  (require '[clojure.spec.alpha :as s] '[expound.alpha :as expound] '[spec-tools.core :as st])
nil
user=> (set! s/*explain-out* expound/printer)
#object[expound.alpha$printer 0x65bcf7c2 "expound.alpha$printer@65bcf7c2"]
user=> (expound/def ::my-num (st/spec pos-int? {:reason "positive"}) (fn [old-msg problem] (str "should be " (:reason problem))))
:user/my-num
user=> (s/explain ::my-num -1)
-- Spec failed --------------------

  -1

should be positive

-- Relevant specs -------

:user/my-num:
  (spec-tools.core/spec
   {:spec clojure.core/pos-int?, :type :long, :reason "positive"})

-------------------------
Detected 1 error
nil
user=>
```

**Comment by ikitommi** [comment]
Hi, and thanks for the efforts on this. Could this work without the `expound/def`? I can change / add new keys to `:problems` so that Expound could find those automatically with a full sentance. For data-specs, I'm thinking of doing a `s/keys` version that doesn't require the spec to be registered globally, enabling runtime generation of specs for multi-tenant systems (currently using Schema for those). Would not like extra registration as it requires qualified names to be invented for all (inline) models.

So, this would be sweet:

```clj
(require '[clojure.spec.alpha :as s] '[expound.alpha :as expound] '[spec-tools.core :as st])
nil
user=> (s/explain (st/spec pos-int? {:reason "positive"}) -1)
-- Spec failed --------------------

  -1

should be positive

-- Relevant specs -------

:user/my-num:
  (spec-tools.core/spec
   {:spec clojure.core/pos-int?, :type :long, :reason "positive"})

-------------------------
Detected 1 error
nil
```

Is there some qualified / expound-spesific keys I could emit to `:problems` to make this work?

**Comment by bhb** [comment]
There is a key you can add to each problem which allows you to completely control the output: :expound.spec.problem/type

Once that is added, you can register multimethods to control printing. 

See this example in spell-spec

https://github.com/bhauman/spell-spec/blob/master/src/spell_spec/expound.cljc

Please note this extension point is very very alpha and may very well change once I move to beta.

Would this work for your use case?

**Comment by bhb** [comment]
Closing due to inactivity. I don't see any demand for this feature.

**Pull request closed without merging**
