### PR TITLE
Add minimal deps.edn

### PR DESCRIPTION
**Pull request by arichiardi**
This is the minimum requirement for being able to use `{:git/url ... :sha ...}`
with expound.

### CODE REVIEW

**Comment by bhb** [comment]
Thanks!!!

**Comment by arichiardi** [comment]
Btw if the colorize PR gets rebased to master, you will have a happy man using that new and easy Clojure feature :smile:

I mean, I have your repo on the disk anyways but trying with the sha is definitely cooler!

**Comment by arichiardi** [comment]
Not sure it needs a rebase actually, will try it out with current situation first.

**Comment by bhb** [comment]
I've merged your commit into `prerelease` branch so it has the `deps.edn` now. I *think* this means you can use with the SHA 59740c46c5a33cfa1257e563ec37b652eae692fd, but I haven't yet tried it. Let me know!

**Pull request merged**
